services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=security_db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=root
    volumes:
#      - secure:/var/lib/postgresql/data
      - ./database_init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
#volumes:
#  secure: